version: '2'
services:
    vault-ssh-helper:
        build: .
        network_mode: "host"
        volumes:
            - /home/vagrant:/home/developer
            - .:/pwd
        user: 1000:1000
        stdin_open: true
        tty: true
        command: --version
